export const DATA = [
    {
        title: 'Produtividade na quarentena',
        description: 'Estar em isolamento social não é algo fácil, é estressante e desgastante por muitos motivos, sejam eles o fato de conviver mais com alguns familiares, a pressão para sermos pessoas produtivas ou simplesmente o medo da pandemia porém, vale ressaltar que para sobrevivermos à essa quarentena é necessário nos mantermos ocupados, envolvidos com alguma atividade.Pensando nisso e tendo ciência que muitos se encontram perdidos, vamos listar aqui algumas dicas para aumentar sua produtividade durante a quarentena e também para cuidar da sua saúde mental',
        categoryColor: '#2e9ae2',
        categoryTitle: 'Treinamentos',
        duration: '1h',
        participants: '6 participantes',
        src: require('../assets/imgs/produtividade-quarentena.webp'),
    },
    {
        title: 'Como lidar com a Covid-19',
        description: 'As consequências da pandemia do novo coronavírus estão causando pressão psicológica e estresse em grande parte da população afetada. As incertezas provocadas pelo covid-19, os riscos de contaminação e a obrigação de isolamento social podem agravar ou gerar problemas mentais, segundo a OMS. Autoridades de saúde e a agência da ONU estão cooperando para conter a disseminação da doença. Mas como ocorre em tempos de crise, a ameaça de contaminação está causando estresse na população. Vamos dar algumas dicas de como superar essa fase',
        categoryColor: '#e64149',
        categoryTitle: 'Workshops',
        duration: '35min',
        participants: '4 participantes',
        src: require('../assets/imgs/covid19.jpg'),
    },
    {
        title: 'Gestão e liderança',
        description: 'As constantes mudanças do mercado exigem que as empresas, além de infraestrutura de qualidade e tecnologias, tenham uma boa liderança, que garanta o sucesso organizacional.Atualmente, os negócios precisam de profissionais capazes de administrar e gerir, tanto os processos, quanto as pessoas. Dessa forma, a organização será capaz de realizar suas atividades com maestria, com uma equipe motivada e que alcance resultados eficazes.',
        categoryColor: '#8d4b93',
        categoryTitle: 'Webinar Online',
        duration: '2h 35min',
        participants: '10 participantes',
        src: require('../assets/imgs/leader.jpg'),
    },
    {
        title: 'Worklife balance',
        description: 'Muitas vezes, o trabalho tem precedência sobre tudo o mais em nossas vidas. Nosso desejo de ter sucesso profissional pode nos levar a deixar de lado nosso próprio bem-estar. Criar um equilíbrio harmonioso entre a vida profissional e a vida profissional é essencial para melhorar não apenas nosso bem-estar físico, emocional e mental, mas também é importante para nossa carreira. Vamos lhe ajudar com isso!',
        categoryColor: '#23cffd',
        categoryTitle: 'Palestras presenciais',
        duration: '35min',
        participants: '4 participantes',
        src: require('../assets/imgs/worlife.webp'),
    },
    {
        title: 'Auto-cuidado emocional',
        description: 'Quando se trata de nossa saúde emocional, uma das melhores dicas é garantir que estamos completamente conectados às nossas emoções. Podemos ser tentados a rejeitar sentimentos como tristeza ou raiva, mas é saudável senti-los, aceitá-los e seguir em frente.Lembre-se de que as emoções não são boas ou ruins. Você não é culpado pelas emoções que sente. O que fará a diferença é exatamente como você se comporta em resposta a elas.',
        categoryColor: '#8d4b93',
        categoryTitle: 'Webinar Online',
        duration: '2d',
        participants: '8 participantes',
        src: require('../assets/imgs/selflove.jpg'),
    },

]